- block:
  - name: read instance data
    shell: >
      . ~/overcloudrc_v3_hailstorm &&
      OS_TENANT_NAME={{ osp_tenant }}
      OS_PROJECT_NAME={{ osp_tenant }}
      OS_PASSWORD={{ root_password }}
      openstack server show -f json {{ inventory_hostname_short }}
    register: instance_data2
    failed_when: instance_data2.stdout == ""
    changed_when: false
  - debug: var=instance_data2

  - block:
    - name: detach additional volumes
      shell: >
        . ~/overcloudrc_v3_hailstorm &&
        OS_TENANT_NAME={{ osp_tenant }}
        OS_PROJECT_NAME={{ osp_tenant }}
        OS_PASSWORD={{ root_password }}
        openstack server remove volume {{ inventory_hostname_short }} {{ item }}
      with_items: "{{ (instance_data2.stdout | from_json)['volumes_attached'] | regexp_replace('id=','') | regexp_replace('\n',':') | regex_findall(':') }}"

    - name: delete additional volumes
      shell: >
        . ~/overcloudrc_v3_hailstorm &&
        OS_TENANT_NAME={{ osp_tenant }}
        OS_PROJECT_NAME={{ osp_tenant }}
        OS_PASSWORD={{ root_password }}
        openstack volume create --size {{ (item.0/1024/1024/1024)|int|abs }} {{ inventory_hostname_short }}-{{ item.1 }} | grep "^| id " | cut -d\| -f3 | awk '{print $1}'
      with_items: "{{ (instance_data2.stdout | from_json)['volumes_attached'] | regexp_replace('id=','') | regexp_replace('\n',':') | regex_findall(':') }}"

    when: ((instance_data2.stdout | from_json )["volumes_attached"]) != ""

  become: yes
  become_user: "{{ hostvars['rhosp-director'].rhosp_stack_user }}"
  delegate_to: rhosp-director
