- name: read instance data
  shell: >
    . ~/overcloudrc_v3_hailstorm &&
    OS_TENANT_NAME={{ osp_tenant }}
    OS_PASSWORD={{ root_password }}
    openstack server list -f json --name {{ inventory_hostname_short }}
  register: instance_data
  failed_when: instance_data.stdout == ""
  changed_when: false
  become: yes
  become_user: "{{ hostvars['rhosp-director'].rhosp_stack_user }}"
  delegate_to: rhosp-director

- name: save floating IP as fact ansible_host
  set_fact:
    ansible_host: "{{ (instance_data.stdout|from_json)[0]['Networks']|regex_replace('internal_'+osp_tenant+'=\\d+\\.\\d+\\.\\d+\\.\\d+,?\\s*','') }}"
    ansible_ssh_common_args: "-i ./binary/{{ hailstorm_ssh_priv_key_file }} -o StrictHostKeyChecking=no"
