---
# this is to prevent the next step from failing
- name: remove standard resolver config (if present)
  lineinfile: dest=/etc/resolv.conf line="nameserver {{ infrastructure_address_default_dns }}" state=absent

# if the following step fails, check to see if the DNS resolution resolves the server's fqdn to the external IP address (in which case it fails)
- name: initial configuration of the IPA servers
  command: ipa-server-install -r "{{ hailstorm_dns_domain|upper }}" -p "{{ ipa_admin_password }}" -a "{{ ipa_admin_password }}" -U --setup-dns --forwarder="{{ infrastructure_address_default_dns }}" --no-dnssec-validation  creates=/etc/dirsrv/slapd-{{ hailstorm_dns_domain|upper|regex_replace('\.','-') }}/dse.ldif
