- block:
    # - include: ipa-firewalld.yml
    #   tags: ['ipa-install']
    - include: ipa-rng-service.yml
      tags: ['ipa-install']
    - include: ipa-ntp-service.yml
      tags: ['ipa-install']
    - include: ipa-configure.yml
      tags: ['ipa-install']
    - include: ipa-dns-records-add.yml
      tags: ['ipa-dns']
    - include: ipa-users-add.yml
      tags: ['ipa-users']
    - include: ipa-groups-add.yml
      tags: ['ipa-groups']
    - include: ipa-users-add-ssh-keys.yml
      tags: ['ipa-ssh']
    - include: ipa-createcertprofile.yml
      tags: ['ipa-certprofile']
  when: mode=="create"
