---
mem: 4096
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  # partition_table:
  #   lvmpv: 29500
  #   swap: 2048
  #   home: 2048
  #   root: 10000
  physvols:
    boot: 500
    rhel: 29500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048
    - name: var
      fstype: "{{ fstype }}"
      mountpoint: /var
      size: 12000


pool_regex: "{{ rhsso_subscription_pool_regex }}"
repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - jb-eap-7.0-for-rhel-7-server-rpms
  - rh-sso-7.1-for-rhel-7-server-rpms
packages:
  - java-1.8.0-openjdk
  - zip
  - postgresql
  - postgresql-jdbc
#  - @rh-sso7
firewalld_rules:
  - HTTPStcp:
   port: 8443
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
   immediate: true

