---
# work around a bug/feature (on the hailstorm side) when delegating, since "inventory_hostname_short"
# will always resolve to the current host, it means that delegating to a string which contain
# "inventory_hostname_short" means it delegates to iteself
ansible_host: "{{Â infrastructure_network_admin.host_prefix | regex_replace('(^.*\\.).*$','\\1') }}{{ hailstorm_number['rhevm'] }}"

mem: 4096
vcpu: 2
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000

pool_regex: "{{ rhev_subscription_pool_regex }}"

repos: "{{ rhevm_repos }}"
packages: rhevm,ovirt-engine-extension-aaa-ldap-setup
