---
mem: "{{ layer2_rhosp_director_mem }}"
vcpu: "{{ layer2_rhosp_director_cpu }}"
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 60
  format: qcow2
  # partition_table:
  #   lvmpv: 59500
  #   swap: 4096
  #   home: 2048
  #   root: 50000
  physvols:
    boot: 500
    rhel: 59500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 4096
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 50000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048

hostname_override: director

nic_attachments:
  - "{{ infrastructure_network_rhosp_provisioning }}"
  - "{{ infrastructure_network_services }}"
  - "{{ infrastructure_network_admin }}"
  - "{{ infrastructure_network_storage }}"
default_route_via: "{{ infrastructure_network_rhosp_provisioning }}"
name_service_via: "{{ infrastructure_network_services }}"

pool_regex: "{{ rhosp_subscription_pool_regex }}"
repos: "{{ rhosp_undercloud_repos }}"

packages: python-tripleoclient,python-rdomanager-oscplugin,python-dracclient,rhosp-director-images,rhosp-director-images-ipa
disable_services:
  - NetworkManager

image_path: /home/stack/images

ironic_rpc_timeout: 600
nova_rpc_timeout: 600

# will be populated during runtime
os_auth: {}


default_overcloud_flavors: [
  {
    "ID": "1",
    "Disk": 1,
    "Is Public": true,
    "VCPUs": 1,
    "Ephemeral": 0,
    "RAM": 512,
    "Name": "m1.tiny"
  },
  {
    "ID": "2",
    "Disk": 20,
    "Is Public": true,
    "VCPUs": 1,
    "Ephemeral": 0,
    "RAM": 2048,
    "Name": "m1.small"
  },
  {
    "ID": "3",
    "Disk": 40,
    "Is Public": true,
    "VCPUs": 2,
    "Ephemeral": 0,
    "RAM": 4096,
    "Name": "m1.medium"
  },
  {
    "ID": "4",
    "Disk": 80,
    "Is Public": true,
    "VCPUs": 4,
    "Ephemeral": 0,
    "RAM": 8192,
    "Name": "m1.large"
  },
  {
    "ID": "5",
    "Disk": 160,
    "Is Public": true,
    "VCPUs": 8,
    "Ephemeral": 0,
    "RAM": 16384,
    "Name": "m1.xlarge"
  }
]
