---
mem: "{{ layer2_satellite_mem }}"
vcpu: "{{ layer2_satellite_cpu }}"
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 200
  format: qcow2
  partition_table:
    lvmpv: 199500
    swap: 4096
    home: 2048
    root: 190000

pool_regex: "{{ satellite_subscription_pool_regex }}"
#poolid: "{{Â satellite_subscription_poolid }}"
repos: "{{ satellite_repos }}"

packages: katello,bind-utils,chrony,katello-agent,vim,screen,iptraf-ng

tdagent_configs:
  - tag: syslog.messages
    path: /var/log/messages
    pos_file: /var/log/td-agent/messages_log.pos
    format: syslog
    permissions:
      - path: /var/log/messages
        mode: o+r
  - tag: httpd.access
    path: /var/log/httpd/access_log
    pos_file: /var/log/td-agent/httpd_access_log.pos
    format: apache2
    permissions:
      - path: /var/log/httpd
        mode: o+xr
      - path: /var/log/httpd/access_log
        mode: o+r
  - tag: httpd.error
    path: /var/log/httpd/error_log
    pos_file: /var/log/td-agent/httpd_error_log.pos
    format: apache2
    permissions:
      - path: /var/log/httpd
        mode: o+xr
      - path: /var/log/httpd/access_log
        mode: o+r

firewalld_rules:
 - DNStcp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - DNSudp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - dhcpsrv:
   port: 67
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - dhcpcli:
   port: 68
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - tftp:
   port: 69
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - http:
   port: 80
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - https:
   port: 443
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - gofer:
   port: 5647
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - AMQP:
   port: 5671
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - puppet:
   port: 8140
   protocol: tcp
   state: enabled
   zone: public
   permanent: true


organization: "Default Organization"
organization_id: "Default_Organization"

product_config:
  - product: "Red Hat Enterprise Linux Server"
    basearch: x86_64
    repos:
      - name: "Red Hat Enterprise Linux 7 Server (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)"
      - name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)"
        releasever: 7Server
      - name: "Red Hat Enterprise Linux 7 Server (Kickstart)"
        releasever: "7.2"
      - name: "Red Hat Satellite Tools 6.1 (for RHEL 7 Server) (RPMs)"
      - name: "Red Hat Enterprise Linux 6 Server (RPMs)"
        releasever: 6Server
      - name: "Red Hat Enterprise Linux 6 Server - Supplementary (RPMs)"
        releasever: 6Server
      - name: "Red Hat Enterprise Linux 6 Server (Kickstart)"
        releasever: "6.7"
      - name: "Red Hat Satellite Tools 6.1 (for RHEL 6 Server) (RPMs)"
  - product: Red Hat OpenStack
    basearch: x86_64
    repos:
      - name: Red Hat Enterprise Linux OpenStack Platform 7.0 director for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat Enterprise Linux OpenStack Platform 7.0 for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat OpenStack Platform 8 director for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat OpenStack Platform 8 for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat OpenStack Platform 8 Operational Tools for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat OpenStack Platform 9 director for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat OpenStack Platform 9 for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat OpenStack Platform 9 Operational Tools for RHEL 7 (RPMs)
        releasever: 7Server
#need manifest WITH satellite
#  - product: Red Hat Satellite
#    basearch: x86_64
#    repos:
#      - name: Red Hat Satellite 6.1 (for RHEL 7 Server) (RPMs)
#        releasever: 7Server
  - product: Red Hat Software Collections for RHEL Server
    basearch: x86_64
    repos:
      - name: Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server
        releasever: 7Server
  - product: Red Hat OpenShift Enterprise
    basearch: x86_64
    repos:
      - name: Red Hat OpenShift Enterprise 3.2 (RPMs)
  - product: Red Hat Enterprise Virtualization
    basearch: x86_64
    repos:
      - name: Red Hat Enterprise Virtualization Management Agents for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat Enterprise Virtualization Manager 3.6 (RPMs)
      - name: Red Hat Virtualization 4 Management Agents for RHEL 7 (RPMs)
        releasever: 7Server
      - name: Red Hat Virtualization Manager 4.0 (RHEL 7 Server) (RPMs)
  - product: JBoss Enterprise Application Platform
    basearch: x86_64
    repos:
      - name: JBoss Enterprise Application Platform 6 (RHEL 6 Server) (RPMs)
        releasever: 6Server


lifecycle_environments:
  - name: 'DEV'
    prior: 'Library'
    description: 'Development'
    label: 'development'
  - name: 'TEST'
    prior: 'DEV'
    description: 'Testing'
    label: 'testing'
  - name: 'PROD'
    prior: 'TEST'
    description: 'Production'
    label: 'production'

content_config:
  - content_view: "CV-OS-RHEL6-SERVER"
    content:
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 6 Server RPMs x86_64 6Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.1 for RHEL 6 Server RPMs x86_64"
    host_collection: "RHEL6"
    override: "rhel-6-server-satellite-tools-6.1-rpms"
    activation_key_subscription_regex: "{{ rhel_subscription_pool_regex }}"

  - content_view: "CV-OS-RHEL7-SERVER"
    content:
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.1 for RHEL 7 Server RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server"
    host_collection: "RHEL7"
    override: "rhel-7-server-satellite-tools-6.1-rpms"
    activation_key_subscription_regex: "{{ rhel_subscription_pool_regex }}"

  - content_view: "CV-RHEV-MANAGER"
    content:
      - product: "Red Hat Enterprise Virtualization"
        repository: "Red Hat Enterprise Virtualization Manager 3.6 RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 6 Server RPMs x86_64 6Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.1 for RHEL 6 Server RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 6 Server - Supplementary RPMs x86_64 6Server"
      - product: "JBoss Enterprise Application Platform"
        repository: "JBoss Enterprise Application Platform 6 RHEL 6 Server RPMs x86_64 6Server"
    override: "rhel-6-server-satellite-tools-6.1-rpms"
    host_collection: "RHEVM"
    activation_key_subscription_regex: "{{ rhev_subscription_pool_regex }}"

  - content_view: "CV-RHEV-HYPERVISOR"
    content:
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.1 for RHEL 7 Server RPMs x86_64"
      - product: "Red Hat Enterprise Virtualization"
        repository: "Red Hat Enterprise Virtualization Management Agents for RHEL 7 RPMs x86_64 7Server"
    override: "rhel-7-server-satellite-tools-6.1-rpms"
    host_collection: "RHEVH"
    activation_key_subscription_regex: "{{ rhev_subscription_pool_regex }}"

  - content_view: "CV-RHOSP"
    content:
      - product: "Red Hat OpenStack"
        repository: "Red Hat OpenStack Platform 9 director for RHEL 7 RPMs x86_64 7Server"
      - product: "Red Hat OpenStack"
        repository: "Red Hat OpenStack Platform 9 for RHEL 7 RPMs x86_64 7Server"
      - product: "Red Hat OpenStack"
        repository: "Red Hat OpenStack Platform 9 Operational Tools for RHEL 7 RPMs x86_64 7Server"
      - product: "Red Hat OpenStack"
        repository: "Red Hat OpenStack Platform 8 director for RHEL 7 RPMs x86_64 7Server"
      - product: "Red Hat OpenStack"
        repository: "Red Hat OpenStack Platform 8 for RHEL 7 RPMs x86_64 7Server"
      - product: "Red Hat OpenStack"
        repository: "Red Hat OpenStack Platform 8 Operational Tools for RHEL 7 RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.1 for RHEL 7 Server RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server"
    override: "rhel-7-server-satellite-tools-6.1-rpms"
    host_collection: "RHOSP"
    activation_key_subscription_regex: "{{ rhosp_subscription_pool_regex }}"

  # - content_view: "CV-RHOSP9"
  #   content:
  #     - product: "Red Hat OpenStack"
  #       repository: "Red Hat OpenStack Platform 9 director for RHEL 7 RPMs x86_64 7Server"
  #     - product: "Red Hat OpenStack"
  #       repository: "Red Hat OpenStack Platform 9 for RHEL 7 RPMs x86_64 7Server"
  #     - product: "Red Hat OpenStack"
  #       repository: "Red Hat OpenStack Platform 9 Operational Tools for RHEL 7 RPMs x86_64 7Server"
  #     - product: "Red Hat Enterprise Linux Server"
  #       repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
  #     - product: "Red Hat Enterprise Linux Server"
  #       repository: "Red Hat Satellite Tools 6.1 for RHEL 7 Server RPMs x86_64"
  #     - product: "Red Hat Enterprise Linux Server"
  #       repository: "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64"
  #     - product: "Red Hat Enterprise Linux Server"
  #       repository: "Red Hat Enterprise Linux 7 Server - Optional RPMs x86_64 7Server"
  #   override: "rhel-7-server-satellite-tools-6.1-rpms"
  #   host_collection: "RHOSP"
  #   activation_key_subscription_regex: "{{ rhosp_subscription_pool_regex }}"

  - content_view: "CV-RHOSE3"
    content:
      - product: "Red Hat OpenShift Enterprise"
        repository: "Red Hat OpenShift Enterprise 3.2 RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server RPMs x86_64 7Server"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Satellite Tools 6.1 for RHEL 7 Server RPMs x86_64"
      - product: "Red Hat Enterprise Linux Server"
        repository: "Red Hat Enterprise Linux 7 Server - Extras RPMs x86_64"
    override: "rhel-7-server-satellite-tools-6.1-rpms"
    host_collection: "RHOSE3"
    activation_key_subscription_regex: "{{ ose_subscription_pool_regex }}"
