---
mem: "{{ layer2_satellite_mem }}"
vcpu: "{{ layer2_satellite_cpu }}"
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 250
  format: qcow2
  physvols:
    boot: 500
    rhel: 249500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 4096
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 240000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048


pool_regex: "{{ satellite_subscription_pool_regex }}"
repos: "{{ satellite_repos }}"

packages: "{% if satellite_version != '6.1' %}satellite,{% endif %}bind-utils,chrony,katello-agent,vim,screen,iptraf-ng"

tdagent_configs:
  - tag: syslog.messages
    path: /var/log/messages
    pos_file: /var/log/td-agent/messages_log.pos
    format: syslog
    permissions:
      - path: /var/log/messages
        mode: o+r
  - tag: httpd.access
    path: /var/log/httpd/access_log
    pos_file: /var/log/td-agent/httpd_access_log.pos
    format: apache2
    permissions:
      - path: /var/log/httpd
        mode: o+xr
      - path: /var/log/httpd/access_log
        mode: o+r
  - tag: httpd.error
    path: /var/log/httpd/error_log
    pos_file: /var/log/td-agent/httpd_error_log.pos
    format: apache_error
    permissions:
      - path: /var/log/httpd
        mode: o+xr
      - path: /var/log/httpd/access_log
        mode: o+r

firewalld_rules:
 - DNStcp:
   port: 53
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - DNSudp:
   port: 53
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - dhcpsrv:
   port: 67
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - dhcpcli:
   port: 68
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - tftp:
   port: 69
   protocol: udp
   state: enabled
   zone: public
   permanent: true
 - http:
   port: 80
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - https:
   port: 443
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - gofer:
   port: 5647
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - AMQP:
   port: 5671
   protocol: tcp
   state: enabled
   zone: public
   permanent: true
 - puppet:
   port: 8140
   protocol: tcp
   state: enabled
   zone: public
   permanent: true


organization: "Default Organization"
organization_id: "Default_Organization"
