---
name: test-rhel6
mem: 2048
vcpu: 2
disk:
  path: test-rhel6.qcow2
  size: 30
  format: qcow2
  partition_table:
    lvmpv: 29500
    swap: 2048
    home: 2048
    root: 10000
nic:
  - ip: 192.168.100.21
    dev: eth0
    network: default
    default_route: true
  - ip: 192.168.103.21
    dev: eth1
    network: admin
    default_route: false
ksdevice: eth1
#hostname is now set in group_vars/all.yml
#hostname: test-rhel6.example.com
#root_password is now set in config/hailstorm_config.yml
#root_password: redhat01
ansible_host: 192.168.103.21
activation_key: AK-CV-OS-RHEL6-SERVER-TEST
pool_regex: "{{ rhel_subscription_pool_regex }}"
