- block:
    - include: configure_sshd.yml
      tags: ['rhel-sshd']
    - include: subscribe_system.yml
      tags: ['rhel-subscribe']
    - include: prepare_host.yml
      tags: ['rhel-prepare']
    - include: configure_firewalld_rules.yml
      tags: ['rhel-firewalld']
    - include: chrony_config.yml
      when: ntp_client == 'chrony'
      tags: ['rhel-ntp']
    - include: ntp_config.yml
      when: ntp_client == 'ntp'
      tags: ['rhel-ntp']
  when: mode=="create"

- block:
    - name: unsubscribe VM
      redhat_subscription: state=absent
      ignore_errors: yes
  when: mode=="destroy"

- block:
    - name: get installed katello ca package name
      command: rpm -qa "katello-ca-consumer*"
      register: pkg
      failed_when: pkg.stdout == ""
    - name: remove katello cert
      yum: state=absent name={{ pkg.stdout }}
    - name: reinstall katello cert
      yum: state=present name="http://{{Â hostvars['satellite'].hostname }}/pub/katello-ca-consumer-latest.noarch.rpm"
  when: mode=="refreshcert"
