- block:
    - include: configure_sshd.yml
    - include: subscribe_system.yml
    - include: prepare_host.yml
    - include: configure_firewalld_rules.yml
    - include: chrony_config.yml
      when: ntp_client == 'chrony'
    - include: ntp_config.yml
      when: ntp_client == 'ntp'
  when: mode=="create"

- block:
    - name: unsubscribe VM
      redhat_subscription: state=absent
      ignore_errors: yes
  when: mode=="destroy"
