# set short and full hostname in the /etc/hosts due our lack of DNS here
- name: add entry to /etc/hosts
  lineinfile: dest=/etc/hosts line="{{ vm_nics[0].ip}} {{ hostname }}  {{ inventory_hostname_short }} "

# - name: run katello-installer
#   shell: katello-installer --foreman-admin-username admin --foreman-admin-password {{ root_password }} {% if http_proxy is defined %}--katello-proxy-url {{ http_proxy.protocol }}://{{ http_proxy.proxyname }} --katello-proxy-port {{ http_proxy.port }}{% endif %} && touch /.katello-is-installed  creates=/.katello-is-installed
- name: run satellite-installer
  shell: satellite-installer --scenario satellite --foreman-admin-username admin --foreman-admin-password {{ root_password }} {% if http_proxy is defined %}--katello-proxy-url {{ http_proxy.protocol }}://{{ http_proxy.proxyname }} --katello-proxy-port {{ http_proxy.port }}{% endif %} && touch /.katello-is-installed  creates=/.katello-is-installed
  register: katello_installed

# create hammer-config-file
- name: create dir /root/.hammer
  file: path=/root/.hammer
    state=directory
    owner=root
    group=root
    mode=0755
  when: katello_installed|changed

- name: hammer_cli_config
  template: src=cli_config.yml.j2
    dest=/root/.hammer/cli_config.yml
    owner=root
    group=root
    mode=0600
#why is the following line commented out? when multiple installs run in parallel, ansible gets confused and resuses a connection to satellite on one physical machine when another is actually targetet. This meant that its hammer cli config did then exist, but with the wrong content... by commenting out we will always overwrite the config with the right content
#  when: katello_installed|changed
