- debug: msg="loading {{ item.name }}"

- block:
    - name: uncompress compressed KVM images
      shell: zcat /tmp/binary/{{ item.image }} >/tmp/{{ item.image|regex_replace('.gz$','') }} creates=/tmp/{{ item.image|regex_replace('.gz$','') }}
      when: item.name not in images.stdout | from_json | map(attribute="Name") | list and item.image | search('\.gz$')
      become_user: "{{ rhosp_stack_user }}"

    - name: convert qcow images to raw
      shell: >
        qemu-img convert -O raw {% if item.image | search('\.gz$') %}/tmp/{{ item.image|regex_replace('.gz$','') }}{% else %}/tmp/binary/{{ item.image }}{% endif %} /tmp/{{ item.image }}.raw creates=/tmp/{{ item.image }}.raw
      when: item.name not in images.stdout | from_json | map(attribute="Name") | list
      become_user: "{{ rhosp_stack_user }}"

    - name: load raw image into glance
      shell: >
        . ~/overcloudrc_v3 &&
        openstack image create
        --public
        --disk-format raw
        --file /tmp/{{ item.image }}.raw
        --property hw_qemu_guest_agent=yes {# enable the QEMU guest agent #}
        --property os_require_quiesce=yes {# send fs-freeze/thaw calls through the QEMU guest agent #}
        "{{ item.name }}"
      # don't do this for now because of https://bugzilla.redhat.com/show_bug.cgi?id=1406442
      # --property hw_scsi_model=virtio-scsi {# add the virtio-scsi controller and get better performance and support for discard operation #}
      # --property hw_disk_bus=scsi {# connect every cinder block devices to that controller #}
      when: item.name not in images.stdout | from_json | map(attribute="Name") | list
      become_user: "{{ rhosp_stack_user }}"

    - name: remove uncompressed images
      file: state=absent path=/tmp/{{ item.image|regex_replace('.gz$','') }}
      become_user: "{{ rhosp_stack_user }}"

    - name: remove raw images
      file: state=absent path=/tmp/{{ item.image }}.raw
      become_user: "{{ rhosp_stack_user }}"
  when: current_lifecycle_env.osp_storage_backend.startswith("ceph")

- name: load qcow2 image into glance
  shell: >
    . ~/overcloudrc_v3 &&
    {% if item.image | search('\.gz$') %}z{% endif %}cat /tmp/binary/{{ item.image }} |
    openstack image create
    --public
    --disk-format qcow2
    "{{ item.name }}"
  become_user: "{{ rhosp_stack_user }}"
  when: not current_lifecycle_env.osp_storage_backend.startswith("ceph") and item.name not in images.stdout | from_json | map(attribute="Name") | list
