- name: mount /tmp/binary
  mount: state=mounted fstype=nfs name=/tmp/binary src="{{ infrastructure_address_nfs_server }}:{{ layer1_binary_dir }}"

- block:
    - name: get image list (default project)
      shell: >
        . ~/overcloudrc_v3 &&
        openstack image list -f json
      register: images
      changed_when: false

    - include: configure_images_instance.yml
      with_items: "{{ current_lifecycle_env.osp_kvm_images }}"

  become: yes
  become_user: "{{ rhosp_stack_user }}"

- name: umount /tmp/binary
  mount: state=unmounted fstype=nfs name=/tmp/binary src="{{ infrastructure_address_nfs_server }}:{{ layer1_binary_dir }}"
