---
mem: "{{ layer2_ceph_mem }}"
vcpu: "{{ layer2_ceph_cpu }}"

disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 30
  format: qcow2

  physvols:
    boot: 500
    rhel: 29500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 10000
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048

repos:
  - rhel-7-server-rpms
  - rhel-7-server-rhceph-2-mon-rpms
  - rhel-7-server-rhceph-2-osd-rpms
  - rhel-7-server-rhceph-2-tools-rpms
  - rhel-7-server-rhscon-2-agent-rpms
  - rhel-7-server-rhscon-2-main-rpms
  - rhel-7-server-rhscon-2-installer-rpms

disable_services:
  - firewalld

pool_regex: "{{ ceph_subscription_pool_regex }}"

nic_attachments:
  - "{{ infrastructure_network_services }}"
  - "{{ infrastructure_network_admin }}"
  - "{{ infrastructure_network_storage }}"
default_route_via: "{{ infrastructure_network_services }}"
name_service_via: "{{ infrastructure_network_services }}"
ksdevice: eth1
ntp_client: ntpd
