---
mem: "{{ layer2_ose3node_mem }}"
vcpu: "{{ layer2_ose3node_cpu }}"

disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 60
  format: qcow2
  # partition_table:
  #   lvmpv: 59500
  #   swap: 2048
  #   home: 2048
  #   root: 10000

  physvols:
    boot: 500
    rhel: 59500
  logvols:
    - name: swap
      fstype: swap
      mountpoint: swap
      size: 2048
    - name: root
      fstype: "{{ fstype }}"
      mountpoint: /
      size: 5120
    - name: home
      fstype: "{{ fstype }}"
      mountpoint: /home
      size: 2048
    - name: var
      fstype: "{{ fstype }}"
      mountpoint: /var
      size: 15360

extra_disk_files: "{% if current_lifecycle_env.ocp_use_cns %}{{ cns_disk_files}}{% else %}[]{% endif %}"

cns_disk_files:
  - path: "{{ inventory_hostname_short }}-extra-1.qcow2"
    size: 60
    format: qcow2
    dev: /dev/vdb
  - path: "{{ inventory_hostname_short }}-extra-2.qcow2"
    size: 60
    format: qcow2
    dev: /dev/vdc
  - path: "{{ inventory_hostname_short }}-extra-3.qcow2"
    size: 60
    format: qcow2
    dev: /dev/vdd
  - path: "{{ inventory_hostname_short }}-extra-4.qcow2"
    size: 60
    format: qcow2
    dev: /dev/vde
