---
# nic_attachments:
#   - "{{ infrastructure_network_services }}"
#   - "{{ infrastructure_network_admin }}"
#   - "{{ infrastructure_network_storage }}"
#   - "{{ infrastructure_network_guests }}"
#   - "{{ infrastructure_network_rhosp_provisioning }}"
# default_route_via: "{{ infrastructure_network_services }}"
# name_service_via: "{{ infrastructure_network_services }}"
#ksdevice: eth1
