mem: "{{ layer2_rhosp_compute_mem }}"
vcpu: "{{ layer2_rhosp_compute_cpu }}"
disk:
  path: "{{ inventory_hostname_short }}.qcow2"
  size: 60
  format: qcow2
skip_install: true
#graphics: vnc,listen=0.0.0.0,password=redhat01

# nic0 needs to be on the provisioning network
nic_attachments:
  - "{{ infrastructure_network_rhosp_provisioning }}"
  - "{{ infrastructure_network_services }}"
  - "{{ infrastructure_network_storage }}"
  - "{{ infrastructure_network_rhosp_internal }}"
  - "{{ infrastructure_network_admin }}"
default_route_via: "{{ infrastructure_network_services }}"
name_service_via: "{{ infrastructure_network_services }}"


extra_disk_files: "{% if current_lifecycle_env.osp_storage_backend=='ceph_hyperconverged' %}{{ ceph_disk_files }}{% else %}[]{% endif %}"

ceph_disk_files:
  - path: "{{ inventory_hostname_short }}-extra-1.qcow2"
    size: 100
    format: qcow2
    dev: /dev/vdb
  - path: "{{ inventory_hostname_short }}-extra-2.qcow2"
    size: 100
    format: qcow2
    dev: /dev/vdc
  - path: "{{ inventory_hostname_short }}-extra-3.qcow2"
    size: 100
    format: qcow2
    dev: /dev/vdd
  - path: "{{ inventory_hostname_short }}-extra-4.qcow2"
    size: 100
    format: qcow2
    dev: /dev/vde
