- block:
    - include: register_overcloud_nodes.yml
      tags: ['register']
    - include: create_overcloud.yml
      tags: ['overcloud-deploy']
      vars:
        templates:
          - commandlineparams-environment.yaml
          - network-isolation-environment.yaml
          - extra-config-post-deployment-environment.yaml
          - extra-config-post-deployment.yaml
          - extra-config-post-deployment-all.sh
          - ceilometer-config-environment.yaml
          - "{% if current_lifecycle_env.osp_use_ceph %}storage-ceph-environment.yaml{% else %}storage-nfs-environment.yaml{% endif %}"
          - firstboot-config-environment.yaml
          - firstboot-config.yaml
          - firstboot-config-rootsshkey.sh
          - rhel-registration-environment.yaml
          - rhel-registration.yaml
          - rhel-registration.sh
          - timezone-environment.yaml
          - hostname-map-environment.yaml
          - schedulerhints-environment.yaml
          - dns-config-environment.yaml
          - tls-enable-environment.yaml
          - tls-inject-trust-anchor-environment.yaml
          - monitoring-environment.yaml
          - logging-environment.yaml
    - include: adapt_to_keystone_v3.yml
      tags: ['overcloud-config-keystone']
    - include: configure_tenants.yml
      tags: ['overcloud-config-tenants']
    - include: configure_user_access.yml
      tags: ['overcloud-config-users']
    - include: configure_neutron.yml
      tags: ['overcloud-config-neutron']
      when: current_lifecycle_env.openstack_version <= 10
    - include: configure_neutron_osp11.yml
      tags: ['overcloud-config-neutron']
      when: current_lifecycle_env.openstack_version >= 11
    - include: configure_security.yml
      tags: ['overcloud-config-security']
    - include: configure_images.yml
      tags: ['overcloud-config-images']
    - include: create_flavors.yml
      tags: ['overcloud-create-flavors']
  when: mode=="create"

- block:
    - include: destroy_overcloud.yml
      tags: ['overcloud-deploy']
    - include: unregister_overcloud_nodes.yml
      tags: ['register']
  when: mode=="destroy"

- block:
    - include: scale_down_via_hostname.yml
      static: no
      vars:
        templates:
          - commandlineparams-environment.yaml
          - network-isolation-environment.yaml
          - extra-config-post-deployment-environment.yaml
          - extra-config-post-deployment.yaml
          - extra-config-post-deployment-all.sh
          - ceilometer-config-environment.yaml
          - storage-nfs-environment.yaml
          - firstboot-config-environment.yaml
          - firstboot-config.yaml
          - firstboot-config-rootsshkey.sh
          - rhel-registration-environment.yaml
          - rhel-registration.yaml
          - rhel-registration.sh
          - timezone-environment.yaml
          - hostname-map-environment.yaml
          - schedulerhints-environment.yaml
          - dns-config-environment.yaml
          - tls-enable-environment.yaml
          - tls-inject-trust-anchor-environment.yaml
          - monitoring-environment.yaml
          - logging-environment.yaml
  when: mode=="reset"
