- block:
    - include: register_overcloud_nodes.yml
      tags: ['register']
    - include: create_overcloud.yml
      tags: ['overcloud-deploy']
    - include: configure_neutron.yml
      tags: ['overcloud-deploy']
  when: mode=="create"

- block:
    - include: destroy_overcloud.yml
      tags: ['overcloud-deploy']
    - include: unregister_overcloud_nodes.yml
      tags: ['register']
  when: mode=="destroy"
