# BASIC CONFIG
root_password: redhat01

# BINARY FILES
hailstorm_ssh_pub_key_file: hailstorm.pub
hailstorm_ssh_priv_key_file: hailstorm
#undercloud_ssh_pub_key_file: undercloud.pub
#undercloud_ssh_priv_key_file: undercloud
rhel6_iso_image: rhel-server-6.8-x86_64-dvd.iso
rhel7_iso_image: rhel-server-7.2-x86_64-dvd.iso
####BEGIN RHOSP
####RHOSP images are now fetched by installing the appropriate director packages - no need to specify them here
####Theses lines remain as long as the legacy code to upload the director images from the control host or layer1 host remains
# rhosp_images:
#   - deploy-ramdisk-ironic-7.3.1-39.tar
#   - discovery-ramdisk-7.3.1-59.tar
#   - overcloud-full-7.3.1-59.tar
rhosp_images:
  - ironic-python-agent-8.0-20160415.1.tar
  - overcloud-full-8.0-20160415.1.tar
####END RHOSP
satellite_manifestfile: manifest.zip
cloudforms_ova_appliance: cfme-rhevm-5.6.1.2-1.x86_64.rhevm.ova
#cloudforms_ova_appliance: cfme-rhevm-5.6.0.13-1.x86_64.rhevm.ova
#cloudforms_ova_appliance: cfme-rhevm-5.5.3.4-1.x86_64.rhevm.ova
#cloudforms_ova_appliance: manageiq-ovirt-devel.ova

osp_kvm_images:
  - image: rhel-guest-image-7.2-20160302.0.x86_64.qcow2
    name: RHEL7
  - image: cirros-0.3.4-x86_64-disk.img
    name: CirrOS
  - image: windows_server_2012_r2_standard_eval_kvm_20151021.qcow2.gz
    name: Windows Server 2012

rhev_templates:
  - image: rhel-guest-image-7.2-20160302.0.x86_64.qcow2
    name: "RHEL7"

# RED HAT SUBSCRIPTION POOLS
#rhel6_subscription_poolid: 8a85f9814f220b7c014f221083430791
#rhel7_subscription_poolid: 8a85f9814f220b7c014f221083430791
#satellite_subscription_poolid: 8a85f9814f220b7c014f2211095208d2
satellite_subscription_pool_regex: "^(Red Hat Satellite Employee Subscription|Red Hat Satellite)$"
rhel_subscription_pool_regex: "^(Employee SKU|Red Hat Enterprise Linux Server.*Unlimited guests.*)$"
rhev_subscription_pool_regex: "^(Employee SKU|Red Hat Enterprise Virtualization.*|Red Hat Enterprise Linux Server.*Unlimited guests.*)$"
rhosp_subscription_pool_regex: "^(Employee SKU|Red Hat Enterprise Linux OpenStack Platform.*)$"
ose_subscription_pool_regex: "^(Employee SKU|OpenShift Enterprise.*)$"
cloudforms_subscription_pool_regex: "^(CloudForms Employee Subscription|Red Hat Enterprise Linux OpenStack Platform.*)$"

# REPOSITORIES
# rhosp_undercloud_repos:
#   - rhel-7-server-rpms
#   - rhel-7-server-optional-rpms
#   - rhel-7-server-extras-rpms
#   - rhel-7-server-openstack-7.0-rpms
#   - rhel-7-server-openstack-7.0-director-rpms
rhosp_undercloud_repos:
  - rhel-7-server-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-openstack-9-rpms
  - rhel-7-server-openstack-9-director-rpms
rhosp_overcloud_repos:
  - rhel-7-server-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-openstack-9-optools-rpms
satellite_repos:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-satellite-{{ satellite_version }}-rpms
rhevm_repos:
  - rhel-6-server-rpms
  - rhel-6-server-supplementary-rpms
  - rhel-6-server-rhevm-3.6-rpms
  - jb-eap-6-for-rhel-6-server-rpms
rhevh_repos:
  - rhel-7-server-rpms
  - rhel-7-server-rhev-mgmt-agent-rpms
ipa_repos:
  - rhel-7-server-rpms
cloudforms_repos:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - cf-me-5.6-for-rhel-7-rpms
ose3_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.2-rpms
ose3_additional_packages: docker
#   - rhel-7-server-ose-3.1-rpms
# ose3_additional_packages: docker-1.8.2
tdagent_rpm:
  "7": https://packages.treasuredata.com/2/redhat/7/x86_64/td-agent-2.2.0-0.x86_64.rpm
  "6": https://packages.treasuredata.com/2/redhat/6/x86_64/td-agent-2.2.0-0.x86_64.rpm


timezone: Europe/Berlin


ipa_user:
  - username: consumer
    password: "{{ root_password }}"
    first: Consumer
    last: User
  - username: approver
    password: "{{ root_password }}"
    first: Approver
    last: User
  - username: developer
    password: "{{ root_password }}"
    first: Developer
    last: User
  - username: rhev-bind-user
    first: rhev
    last: binduser
    password: "{{ root_password }}"
  - username: ose-bind-user
    first: ose
    last: binduser
    password: "{{ root_password }}"
  - username: osp-bind-user
    first: osp
    last: binduser
    password: "{{ root_password }}"
  - username: cfme-bind-user
    first: cfme
    last: binduser
    password: "{{ root_password }}"


ipa_group:
  - groupname: demo-admin
    members:
      - admin
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=1
  - groupname: demo-all
    members:
      - admin
      - developer
      - consumer
      - approver
      - cfme-bind-user
      - rhev-bind-user
      - ose-bind-user
      - osp-bind-user
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=6
  - groupname: demo-consumer
    members:
      - admin
      - developer
      - consumer
      - approver
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=2
  - groupname: demo-approver
    members:
      - approver
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=3
  - groupname: demo-developer
    members:
      - developer
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=4
  - groupname: service-accounts
    members:
      - cfme-bind-user
      - rhev-bind-user
      - ose-bind-user
      - osp-bind-user
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=0

osp_domain_name: hailstorm
osp_projects:
  - demo
  - demo1
osp_admin_user:
  - cfme-bind-user
  - admin
osp_member_user:
  - consumer
  - developer
  - approver
