# BASIC CONFIG
root_password: redhat01

# BINARY FILES
hailstorm_ssh_pub_key_file: hailstorm.pub
hailstorm_ssh_priv_key_file: hailstorm
#undercloud_ssh_pub_key_file: undercloud.pub
#undercloud_ssh_priv_key_file: undercloud
satellite_manifestfile: manifest.zip
tower_license_key_file: tower_license.json

lifecycle_environments:
  - name: 'DEV'
    prior: 'Library'
    description: 'Development'
    label: 'development'
    content_view_date_filter:
      "*": "2017-01-16"
    errata_for_demo_scenario:
      - RHSA-2016:1940
    satellite_version: 6.2.5
    openshift_version: 3.3
    openstack_version: 10
    osp_controlled_node_placement: false
    cloudforms_version: 5.6
    cloudforms_ova_appliance: cfme-rhevm-5.6.2.2-1.x86_64.rhevm.ova
    rhel6_iso_image: rhel-server-6.8-x86_64-dvd.iso
    rhel7_iso_image: rhel-server-7.3-x86_64-dvd.iso
    kvm_images:
      RHEL7: rhel-guest-image-7.2-20160302.0.x86_64.qcow2
      CirrOS: cirros-0.3.4-x86_64-disk.img
      Windows: windows_server_2012_r2_standard_eval_kvm_20151021.qcow2.gz
    cfme_rhconsulting_scripts_hash: 4a9c5478e58181c099cd9f1dce00ae09c55f2298
    ansible_tower_url: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-3.0.3.tar.gz

  - name: 'TEST'
    prior: 'DEV'
    description: 'Testing'
    label: 'testing'
    content_view_date_filter:
      "*": "2016-10-21"
    errata_for_demo_scenario:
      - RHSA-2016:1940
    satellite_version: 6.2.4
    openshift_version: 3.3
    openstack_version: 9
    osp_controlled_node_placement: false
    cloudforms_version: 5.6
    cloudforms_ova_appliance: cfme-rhevm-5.6.1.2-1.x86_64.rhevm.ova
    rhel6_iso_image: rhel-server-6.8-x86_64-dvd.iso
    rhel7_iso_image: rhel-server-7.2-x86_64-dvd.iso
    kvm_images:
      RHEL7: rhel-guest-image-7.2-20160302.0.x86_64.qcow2
      CirrOS: cirros-0.3.4-x86_64-disk.img
      Windows: windows_server_2012_r2_standard_eval_kvm_20151021.qcow2.gz
    cfme_rhconsulting_scripts_hash: 4a9c5478e58181c099cd9f1dce00ae09c55f2298
    ansible_tower_url: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-3.0.2.tar.gz

  - name: 'PROD'
    prior: 'TEST'
    description: 'Production'
    label: 'production'
    content_view_date_filter:
      "*": "2016-09-28"
      "CV-RHOSE3": "2016-10-21"
      "CV-RHOSE3-CLIENT": "2016-10-21"
      "CV-RHOSP": "2016-09-12"
    errata_for_demo_scenario:
      - RHSA-2016:1940
    satellite_version: 6.2.4
    openshift_version: 3.3
    openstack_version: 9
    osp_controlled_node_placement: false
    cloudforms_version: 5.6
    cloudforms_ova_appliance: cfme-rhevm-5.6.1.2-1.x86_64.rhevm.ova
    rhel6_iso_image: rhel-server-6.8-x86_64-dvd.iso
    rhel7_iso_image: rhel-server-7.2-x86_64-dvd.iso
    kvm_images:
      RHEL7: rhel-guest-image-7.2-20160302.0.x86_64.qcow2
      CirrOS: cirros-0.3.4-x86_64-disk.img
      Windows: windows_server_2012_r2_standard_eval_kvm_20151021.qcow2.gz
    cfme_rhconsulting_scripts_hash: 4a9c5478e58181c099cd9f1dce00ae09c55f2298
    ansible_tower_url: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-3.0.2.tar.gz

current_lifecycle_env: "{{ (lifecycle_environments|selectattr('name','match','^'+stage+'$')|list)[0] }}"

osp_kvm_images:
  - name: RHEL7
    image: "{{ current_lifecycle_env.kvm_images['RHEL7'] }}"
  - name: CirrOS
    image: "{{ current_lifecycle_env.kvm_images['CirrOS'] }}"
  - name: Windows Server 2012
    image: "{{ current_lifecycle_env.kvm_images['Windows'] }}"

rhev_templates:
  - name: RHEL7
    image: "{{ current_lifecycle_env.kvm_images['RHEL7'] }}"

# RED HAT SUBSCRIPTIONS
satellite_subscription_pool_regex: "^(Red Hat Satellite Employee Subscription|Red Hat Satellite)$"
rhel_subscription_pool_regex: "^(Employee SKU|Red Hat Enterprise Linux Server.*Unlimited guests.*)$"
sap_subscription_pool_regex: "^(Employee SKU|Red Hat Enterprise Linux Server for SAP HANA.*)$"
rhev_subscription_pool_regex: "^(Employee SKU|Red Hat Enterprise Virtualization.*|Red Hat Enterprise Linux Server.*Unlimited guests.*)$"
rhosp_subscription_pool_regex: "^(Employee SKU|Red Hat Enterprise Linux OpenStack Platform.*)$"
ose_subscription_pool_regex: "^(Employee SKU|OpenShift Enterprise.*)$"
cloudforms_subscription_pool_regex: "^(CloudForms Employee Subscription|Red Hat Enterprise Linux OpenStack Platform.*)$"

# REPOSITORIES
rhosp_undercloud_repos:
  - rhel-7-server-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-openstack-{{ current_lifecycle_env.openstack_version }}-rpms
  - rhel-7-server-openstack-{{ current_lifecycle_env.openstack_version }}-director-rpms
rhosp_overcloud_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-openstack-{{ current_lifecycle_env.openstack_version }}-rpms
  - rhel-7-server-openstack-{{ current_lifecycle_env.openstack_version }}-optools-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-ha-for-rhel-7-server-rpms
satellite_repos:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-7-server-satellite-{{ current_lifecycle_env.satellite_version[0:3] }}-rpms
rhevm_repos:
  - rhel-6-server-rpms
  - rhel-6-server-supplementary-rpms
  - rhel-6-server-rhevm-3.6-rpms
  - jb-eap-6-for-rhel-6-server-rpms
rhevh_repos:
  - rhel-7-server-rpms
  - rhel-7-server-rhev-mgmt-agent-rpms
ipa_repos:
  - rhel-7-server-rpms
cloudforms_repos:
  - rhel-7-server-rpms
  - rhel-server-rhscl-7-rpms
  - cf-me-{{ current_lifecycle_env.cloudforms_version }}-for-rhel-7-rpms
ose3_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-{{ current_lifecycle_env.openshift_version }}-rpms
ose3_additional_packages: docker

tdagent_rpm:
  "7": https://packages.treasuredata.com/2/redhat/7/x86_64/td-agent-2.2.0-0.x86_64.rpm
  "6": https://packages.treasuredata.com/2/redhat/6/x86_64/td-agent-2.2.0-0.x86_64.rpm

epel_rpm: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

cfme_rhconsulting_scripts_repo: https://github.com/rhtconsulting/cfme-rhconsulting-scripts.git

timezone: Europe/Berlin


ipa_user:
  - username: admin
    password: "{{ root_password }}"
    first: Admin
    last: User
  - username: consumer
    password: "{{ root_password }}"
    first: Consumer
    last: User
  - username: approver
    password: "{{ root_password }}"
    first: Approver
    last: User
  - username: developer
    password: "{{ root_password }}"
    first: Developer
    last: User
  - username: rhev-bind-user
    first: rhev
    last: binduser
    password: "{{ root_password }}"
  - username: ose-bind-user
    first: ose
    last: binduser
    password: "{{ root_password }}"
  - username: osp-bind-user
    first: osp
    last: binduser
    password: "{{ root_password }}"
  - username: cfme-bind-user
    first: cfme
    last: binduser
    password: "{{ root_password }}"
  - username: tower-bind-user
    first: tower
    last: binduser
    password: "{{ root_password }}"


ipa_group:
  - groupname: demo-admin
    members:
      - admin
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=1
  - groupname: demo-all
    members:
      - admin
      - developer
      - consumer
      - approver
      - cfme-bind-user
      - rhev-bind-user
      - ose-bind-user
      - osp-bind-user
      - tower-bind-user
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=6
  - groupname: demo-consumer
    members:
      - admin
      - developer
      - consumer
      - approver
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=2
  - groupname: demo-approver
    members:
      - approver
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=3
  - groupname: demo-developer
    members:
      - developer
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=4
  - groupname: service-accounts
    members:
      - cfme-bind-user
      - rhev-bind-user
      - ose-bind-user
      - osp-bind-user
    pwpolicy: --maxlife=20000 --minlife=0 --history=0 --maxfail=0 --priority=0

osp_domain_name: hailstorm
osp_projects:
  - demo-vms
  - demo-infra
osp_admin_user:
  - cfme-bind-user
  - admin
osp_member_user:
  - consumer
  - developer
  - approver
