layer1_ansible_host: inf43.coe.muc.redhat.com
hailstorm_dns_domain: example.com

disable_registration_against_satellite: true

# if this attribute is present, the binaries (except for the SSH keys)
# will be copied from the layer1 host instead of the control host
# you need to ensure they are there before running the playbook
layer1_binary_dir: /home/wrichter/binary
layer1_qcow_storage:
  poolname: 'ocz'
  path: /mnt/ocz/images

nfs_kickstart_folder: /srv/kickstart
nfs_rhev_data_domain_path: /mnt/ocz/rhev-sd1
nfs_rhev_iso_domain_path: /mnt/ocz/rhev-iso1
nfs_rhev_export_domain_path: /mnt/ocz/rhev-export1

layer2_rhev_hypervisor_mem: 8192
layer2_rhev_hypervisor_cpu: 4

layer2_rhosp_director_mem: 8192
layer2_rhosp_director_cpu: 2
layer2_rhosp_control_mem: 6144
layer2_rhosp_control_cpu: 4
layer2_rhosp_compute_mem: 8192
layer2_rhosp_compute_cpu: 4

layer2_satellite_mem: 8192
layer2_satellite_cpu: 4

layer2_ose3node_mem: 2048
layer2_ose3node_cpu: 2
layer2_ose3master_mem: 2048
layer2_ose3master_cpu: 2
layer2_ose3lb_mem: 1024
layer2_ose3lb_cpu: 2

external_network_config:

# if a property http_proxy is defined, satellite will be configured to sync via http_proxy
http_proxy:
  name: proxy.coe.muc.redhat.com
  port: 3128
  protocol: https
