layer1_ansible_host: storm1.coe.muc.redhat.com
hailstorm_dns_domain: hailstorm1.coe.muc.redhat.com

disable_registration_against_satellite: true

# if this attribute is present, the binaries (except for the SSH keys)
# will be copied from the layer1 host instead of the control host
# you need to ensure they are there before running the playbook
layer1_binary_dir: /var/hailstorm/binary
layer1_qcow_storage:
  poolname: 'sata'
  path: /var/hailstorm/images

nfs_kickstart_folder: /var/hailstorm/kickstart
nfs_rhev_data_domain_path: /var/hailstorm/rhev-data1
nfs_rhev_iso_domain_path: /var/hailstorm/rhev-iso1
nfs_rhev_export_domain_path: /var/hailstorm/rhev-export1

nfs_ose3_pv_path: /var/hailstorm/ose3-pv

layer2_rhev_manager_mem: 16384
layer2_rhev_manager_cpu: 4
layer2_rhev_hypervisor_mem: 32768
layer2_rhev_hypervisor_cpu: 8

layer2_rhosp_director_mem: 16384
layer2_rhosp_director_cpu: 4
layer2_rhosp_control_mem: 8192
layer2_rhosp_control_cpu: 4
layer2_rhosp_compute_mem: 32768
layer2_rhosp_compute_cpu: 8

layer2_satellite_mem: 16384
layer2_satellite_cpu: 4

layer2_ose3node_mem: 16384
layer2_ose3node_cpu: 8
layer2_ose3master_mem: 4096
layer2_ose3master_cpu: 4

# if a property http_proxy is defined, satellite will be configured to sync via http_proxy
http_proxy:
  proxyname: proxy.coe.muc.redhat.com
  port: 3128
  protocol: https
