
# - debug: msg="Updating the node selector for the default namespace"
# - name: Set the node-selector for the default namespace
#   shell: "oc patch ns/openshift-infra --api-version=v1 -p '{\"metadata\": {\"annotations\": {\"openshift.io/node-selector\":\"region=infra\"}}}'"

- name: check replicationcontrollers in openshift-infra ns
  command: oc get rc -n openshift-infra
  register: rc
  changed_when: false

- block:

    - name: Check existing service accounts
      shell: oc get serviceaccounts -n openshift-infra | awk '{ print $1 }'
      register: metrics_sa
      changed_when: false

    - name: Create service account for metrics deployer
      shell: "echo '{\"apiVersion\": \"v1\",\"kind\": \"ServiceAccount\",\"metadata\": {\"name\": \"metrics-deployer\"}, \"secrets\": [{\"name\": \"metrics-deployer\"}] }' | oc create -f - -n openshift-infra"
      when: "'metrics-deployer' not in metrics_sa.stdout_lines"

    - name: Grant edit permission on project openshift-infra for the service account metric-deployer
      command: oadm policy add-role-to-user edit system:serviceaccount:openshift-infra:metrics-deployer -n openshift-infra

    - name: Grant Heapster service account the cluster-reader permission to read the stats
      command: oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:openshift-infra:heapster -n openshift-infra

    - name: Check existing secrets
      shell: oc get secrets -n openshift-infra | awk '{ print $1 }'
      register: metrics_secrets
      changed_when: false

    - name: Create a "dummy" secret that does not specify a certificate value for the metrics deployer
      command: oc secrets new metrics-deployer nothing=/dev/null -n openshift-infra
      when: "'metrics-deployer' not in metrics_secrets.stdout_lines"

    # - name: get ose version
    #   shell: oc version | awk '/^oc/{ print substr($2,0,4) }'
    #   register: version_tag
    #   changed_when: false

    - name: Process the metrics deployer
      #shell: oc process metrics-deployer-template -n openshift -v IMAGE_VERSION={{ version_tag.stdout }},MASTER_URL=https://openshift.{{ hailstorm_dns_domain }}:8443,HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.{{ ocp_apps_dns_domain }},USE_PERSISTENT_STORAGE=true,CASSANDRA_PV_SIZE=5Gi | oc create -n openshift-infra -f -
      #shell: oc process metrics-deployer-template -n openshift -v IMAGE_VERSION={{ version_tag.stdout }},MASTER_URL=https://openshift.{{ hailstorm_dns_domain }}:8443/,HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.{{ ocp_apps_dns_domain }},USE_PERSISTENT_STORAGE=false | oc create -n openshift-infra -f -
      shell: >
        oc process metrics-deployer-template -n openshift
        {% if current_lifecycle_env.openshift_version >= 3.4 %}-v IMAGE_VERSION=v3.4{% endif %}
        -v HAWKULAR_METRICS_HOSTNAME=hawkular-metrics.{{ ocp_apps_dns_domain }}
        -v USE_PERSISTENT_STORAGE=true
        -v CASSANDRA_PV_SIZE=5Gi | oc create -n openshift-infra -f -
  when: "'hawkular-metrics' not in rc.stdout"
