- name: check IPA is available
  wait_for: host={{ inventory_hostname }} port=22 timeout=1
  register: ipa_available
  ignore_errors: true

- name: copy certificate of IPA
  command: cat /etc/ipa/ca.crt
  delegate_to: ipa
  register: certificate
  changed_when: false
  failed_when: certificate.stdout == ''
  when: ipa_available|success

- name: ensure that /etc/origin/master directory exists
  file: dest=/etc/origin/master state=directory

- name: create the cert on the OSE installer
  copy: content="{{ certificate.stdout }}" dest=/etc/origin/master/ipa-ca.crt
  when: ipa_available|success

- name: create certificate files
  copy: content="{{ item.value }}" dest="/root/{{ item.name }}" mode="400"
  when: openshift_key is defined and openshift_cert is defined
  with_items:
    - name: openshift.key
      value: "{{ openshift_key }}"
    - name: openshift.crt
      value: "{{ openshift_cert }}"
    - name: openshift-ca.crt
      value: "{{ openshift_cacert }}"

- name: create /etc/ansible/hosts
  template: src=hosts.j2 dest=/etc/ansible/hosts
  register: ansible_hosts

- block:
    - name: start IPTables services on installer (to prevent playbook from hanging when it enables the service)
      service: name=iptables state=started enabled=yes

    - name: pause for IPTables to react
      pause: seconds=15

    - name: run installer playbook
      shell: ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml 2>&1 >~/openshift_install.log
      async: 7200
      poll: 0
      tags: ['playbook']
      register: playbook

    - name: check on installer playbook completed
      async_status: jid={{ playbook.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 480
      delay: 15
  when: ansible_hosts|changed
