---
#### Ansible Tower ####

# - hosts: layer1
#   remote_user: root
#   gather_facts: false
#   pre_tasks:
#     - setup:
#       tags: [ 'layer1', 'tower' ]
#   roles:
#     - role: layer1_tower
#       tags: [ 'tower', layer1 ]
#       mode: create

- hosts: tower
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'tower', 'vm' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'tower', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'tower', 'rhel' ], mode: create }
    - { role: layer2_ansibletower, tags: [ 'layer2', 'tower', 'tower-install' ], mode: create }
    - { role: layer2_ansibletower_l2inventory, tags: [ 'layer2', 'tower', 'tower-layer2' ], mode: create, inventoryname: "Hailstorm", credentialname: "Hailstorm L2 SSH" }
    - { role: layer2_ipa_certificate, tags: ['layer2', 'tower',  'tower-certificate'], mode: create }
    - { role: layer2_ansibletower_certificate, tags: ['layer2', 'tower',  'tower-certificate'], mode: create }
