- hosts: rhevm
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_rhevm_ldap_demopermissions, tags: [ 'layer2', 'rhev', 'rhevm', 'rhevm-ldap' ], mode: create }

- hosts: lookbusy-rhev
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_vm_on_rhev, tags: [ 'layer3', 'lookbusy', 'lookbusy-rhev', 'vm'], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer3', 'lookbusy', 'lookbusy-rhev', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer3', 'lookbusy', 'lookbusy-rhev', 'rhel'], mode: create }
    - { role: layer3_lookbusy, tags: [ 'layer3', 'lookbusy', 'lookbusy-rhev' ], mode: create }

- hosts: lookbusy-osp
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_vm_on_openstack, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp', 'vm'], mode: create }
    - { role: layer2_rhel, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp', 'rhel'], mode: create }
    - { role: layer3_lookbusy, tags: [ 'layer3', 'lookbusy', 'lookbusy-osp' ], mode: create }

- hosts: rhosp-director
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_rhosp_overcloud_demo_content, tags: [ 'layer2', 'rhosp', 'overcloud', 'democontent' ], mode: create }

- hosts: cloudforms
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer3_cloudforms_content, tags: [ 'layer3', 'cf', 'cfme-content' ], mode: create, content_location: "../CloudForms-Internals" }

- hosts: ose3-installer
  remote_user: root
  gather_facts: false
  roles:
    - { role: layerX_openshift_devops_tools, tags: [layer2, 'ose3', 'ose3-devops'], mode: create }
    - { role: layerX_openshift_demo_monster, tags: [layer2, 'ose3', 'ose3-demo', 'ose3-demo-ticketmonster'], mode: create }
    - { role: layerX_openshift_demo_coolstore, tags: [layer2, 'ose3', 'ose3-demo', 'ose3-demo-coolstore'], mode: create, when: current_lifecycle_env.openshift_version >= 3.5 }
    - { role: layerX_openshift_demo_wordpress, tags: [layer2, 'ose3', 'ose3-demo', 'ose3-demo-wordpress'], mode: create }
    - { role: layerX_openshift_demo_amq, tags: [layer2, 'ose3', 'ose3-demo-amq'], mode: create }
    - { role: layerX_openshift_cfme_mwmgr, tags: [layer2, 'ose3', 'ose3-cfme-mwmgr'], mode: create }

- hosts: dev-client
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'dev-client', 'ose3', 'vm' ], mode: create }
    - { role: layer2_rhel_reconfigure_dns, tags: [ 'layer2', 'dev-client',  'ose3', 'dns' ], mode: create, nameserver: "{{ hostvars['ipa'].vm_nics[0].ip }}" }
    - { role: layer2_rhel, tags: [ 'layer2', 'dev-client',  'ose3', 'rhel' ], mode: create }
    - { role: layerX_ipa_client, tags: [ 'layer2', 'dev-client',  'ose3', 'ipa-client' ], mode: create }
    - { role: layerX_openshift_demo_redhatmsa_on_devclient, tags: [ 'layer2', 'dev-client',  'ose3', 'msademo' ], mode: create }

- hosts: tower
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_ansibletower_jobtemplates, tags: [ 'layer2', 'tower', 'tower-content' ], mode: create, content_location: "../Tower-internals", project_dir: "Hailstorm", inventoryname: "Hailstorm" }
