---

#### OpenShift ####

- hosts: ose3
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'ose3', 'vm' ], mode: stop }

#### RHEV ####

- hosts: rhev
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhev', 'vm' ], mode: stop }

#### IPA ####

- hosts: ipa
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'ipa', 'vm' ], mode: stop }

#### SATELLITE ####

- hosts: satellite
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'satellite', 'vm' ], mode: stop }

- hosts: test-rhel
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'satellite', 'vm' ], mode: stop }


#### OPENSTACK ####

- hosts: rhosp-all
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'rhosp', 'vm' ], mode: stop }

#### EFK ####

- hosts: efk
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'efk', 'vm' ], mode: stop }

#### INFRASTRUCTURE ####

- hosts: infrastructure
  remote_user: root
  gather_facts: false
  roles:
    - { role: layer2_vms, tags: [ 'layer2', 'infrastructure', 'vm' ], mode: stop }
