- block:
    - name: log in to openshift
      shell: oc login --insecure-skip-tls-verify https://{{ openshift_master_api_host_and_port }} --username=developer --password={{ root_password }}
      tags: ['login']
    - name: get git route
      shell:  oc get route -n devops-tools git | awk '/^git/ { print $2 }'
      changed_when: false
      failed_when: gitroute.stdout==""
      register: gitroute
    - name: create ~/git directory
      file: state=directory path="~/git/ose3-ticket-monster "
      tags: ['git']
      register: gitdir
    - name: get git remote server
      shell: cd ~/git/ose3-ticket-monster && git remote get-url origin | awk 'match($0, /\@.*/) { print substr($0, RSTART+1, RLENGTH-25) }'
      register: git_remote_server
      when: not gitdir|changed
      changed_when: false
    - block:
        - name: remove existing ticketmonster repo
          file: state=absent path="~/git/ose3-ticket-monster"
          tags: ['git']
        - name: clone ticketmonster repo
          git: repo=http://{{ gitroute.stdout }}/ose3-ticket-monster.git dest=~/git/ose3-ticket-monster
          tags: ['git']
      when: gitdir|changed or git_remote_server.stdout != gitroute.stdout
    - name: change repo remote URL
      shell: cd ~/git/ose3-ticket-monster && git remote set-url origin http://$(oc whoami ):$(oc whoami -t)@{{ gitroute.stdout }}/ose3-ticket-monster.git
    - name: revert git repo to known state & push
      shell: cd ~/git/ose3-ticket-monster && git reset --hard 6de7839dcc201abe619fcee184a146b85a1b9ed0 && git push -f origin master
    # - name: remove floating IP ranges from ~/.ssh/known_hosts
    #   shell:
  when: demo=="short"
