- block:
    - name: create ~/git directory
      file: state=directory path="~/git"
      tags: ['git']
    - name: remove existing ticketmonster repo
      file: state=absent path="~/git/ose3-ticket-monster"
      tags: ['git']
    - name: clone ticketmonster repo
      git: repo=http://git-devops-tools.apps.{{ hailstorm_dns_domain }}/ose3-ticket-monster.git dest=~/git/ose3-ticket-monster
      tags: ['git']
    - name: log in to openshift
      shell: oc login https://openshift.{{ hailstorm_dns_domain }}:8443 --username=developer --password={{Â root_password }}
    - name: change repo remote URL
      shell: cd ~/git/ose3-ticket-monster && git remote set-url origin http://developer:$(oc whoami -t)@git-devops-tools.apps.{{ hailstorm_dns_domain }}/ose3-ticket-monster.git
    - name: revert git repo to known state & push
      shell: cd ~/git/ose3-ticket-monster && git reset --hard 6de7839dcc201abe619fcee184a146b85a1b9ed0 && git push -f origin master
    # - name: remove floating IP ranges from ~/.ssh/known_hosts
    #   shell:
  when: demo=="short"
