- name: granting anyuid scc to redhat-msa default users
  shell: oadm policy -n redhat-msa add-scc-to-user anyuid -z system:serviceaccount:redhat-msa:default
  delegate_to: "{{Â groups['ose3-installer'][0] }}"
