#upload images to Glance
- name: create image directory
  file: state=directory path={{ image_path }}
  become: yes
  become_user: "{{ rhosp_stack_user }}"
- name: count registered openstack images
  shell: . ~/stackrc && openstack image list -f csv | wc -l
  register: image_count
  changed_when: false

# VARIANT 1 - copy images from control host
- block:
  - name: unpack rhosp images
    unarchive: src=../binary/{{ image }} dest={{ image_path }}
    become: yes
    become_user: "{{ rhosp_stack_user }}"
    with_items: "{{ rhosp_images }}"
  when: (layer1_binary_dir is not defined) and (image_count.stdout | int < 2)

# VARIANT 2 - copy images from layer1 host
- block:
  #TODO not very nice - we change the layer1 host (create ssh key) in a layer2 role
  - name: ensure that root has an ssh key set
    user: name=root generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
    delegate_to: "{{ infrastructure_delegate_local_content_host }}"
  - name: read layer1 root ssh pub key
    shell: cat /root/.ssh/id_rsa.pub
    register: layer1_ssh_pub_key
    delegate_to: "{{ infrastructure_delegate_local_content_host }}"
    changed_when: false
  - name: add layer1 root ssh pub key to rhosp-director
    authorized_key: user=root key={{ layer1_ssh_pub_key.stdout }}

  - name: copy rhosp images from layer1
    synchronize: mode=push src={{Â layer1_binary_dir }}/{{ item }} dest=/tmp/{{ item }}
    delegate_to: "{{ infrastructure_delegate_local_content_host }}"
    with_items: "{{ rhosp_images }}"

  - name: unpack rhosp image
    unarchive: src=/tmp/{{ item }} dest={{ image_path }} copy=no
    become: yes
    become_user: "{{ rhosp_stack_user }}"
    with_items: "{{ rhosp_images }}"

  - name: remove rhosp images from /tmp
    file: path=/tmp/{{ item }} state=absent
    with_items: "{{ rhosp_images }}"
  when: (layer1_binary_dir is defined) and (image_count.stdout | int < 2)

- name: upload images to glance
  shell: . ~/stackrc && openstack overcloud image upload --image-path "{{ image_path }}"
  become: yes
  become_user: "{{ rhosp_stack_user }}"
  when: image_count.stdout | int < 2
